# Generated by Django 3.1 on 2023-11-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
