# Generated by Django 3.1 on 2023-11-25 18:23

from django.db import migrations, models
import sell_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_api', '0002_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('icon', models.ImageField(blank=True, upload_to=sell_api.models.category_image_path)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=sell_api.models.product_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=models.SET(sell_api.models.get_default_product_category), related_name='product_lists', to='sell_api.productcategory')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('-created_at',),
            },
        ),
    ]
