# Generated by Django 3.1 on 2023-12-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell_api', '0007_auto_20231209_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('status', models.CharField(choices=[('Failed', 'FAILED'), ('Pending', 'PENDING'), ('Success', 'SUCCESS')], max_length=55)),
                ('payment_method', models.CharField(choices=[('Credit card', 'CC'), ('Cash on Delivery', 'COD'), ('MoMo', 'MM')], max_length=55)),
                ('amount', models.FloatField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sell_api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
